config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions' }
  resources :ingestions
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingestion.rb
class Ingestion < ApplicationRecord
  belongs_to :user

  validates :dateAndTime, presence: true

  VALID_METHODS = ['smoke', 'vape', 'drink', 'gummie', 'chocolate']

  validates :method, presence: true, inclusion: { in: VALID_METHODS }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ingestions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingestions_controller.rb
class IngestionsController < ApplicationController
  before_action :set_ingestion, only: %i[ show edit update destroy ]

  # GET /ingestions or /ingestions.json
  def index
    @ingestions = Ingestion.all
  end

  # GET /ingestions/1 or /ingestions/1.json
  def show
  end

  # GET /ingestions/new
  def new
    @ingestion = Ingestion.new
  end

  # GET /ingestions/1/edit
  def edit
  end

  # POST /ingestions or /ingestions.json
  def create
    @ingestion = Ingestion.new(ingestion_params)

    respond_to do |format|
      if @ingestion.save
        format.html { redirect_to ingestion_url(@ingestion), notice: "Ingestion was successfully created." }
        format.json { render :show, status: :created, location: @ingestion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingestions/1 or /ingestions/1.json
  def update
    respond_to do |format|
      if @ingestion.update(ingestion_params)
        format.html { redirect_to ingestion_url(@ingestion), notice: "Ingestion was successfully updated." }
        format.json { render :show, status: :ok, location: @ingestion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingestions/1 or /ingestions/1.json
  def destroy
    @ingestion.destroy

    respond_to do |format|
      format.html { redirect_to ingestions_url, notice: "Ingestion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingestion
      @ingestion = Ingestion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingestion_params
      params.require(:ingestion).permit(:dateAndTime, :user_id, :method, :strain)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingestions_helper.rb
module IngestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingestions/_form.html.erb
<%= form_with(model: ingestion) do |form| %>
  <% if ingestion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingestion.errors.count, "error") %> prohibited this ingestion from being saved:</h2>

      <ul>
        <% ingestion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dateAndTime, style: "display: block" %>
    <%= form.datetime_field :dateAndTime %>
  </div>

  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div>
    <%= form.label :method, style: "display: block" %>
    <%= form.text_field :method %>
  </div>

  <div>
    <%= form.label :strain, style: "display: block" %>
    <%= form.text_field :strain %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingestions/_ingestion.html.erb
<div id="<%= dom_id ingestion %>">
  <p>
    <strong>Date and Time:</strong>
    <%= ingestion.dateAndTime %>
  </p>

  <p>
    <strong>User:</strong>
    <%= User.find(ingestion.user_id).name %>
  </p>

  <p>
    <strong>Method:</strong>
    <%= ingestion.method %>
  </p>

  <p>
    <strong>Strain:</strong>
    <%= ingestion.strain %>
  </p>

</div>

app/views/ingestions/edit.html.erb
<h1>Editing ingestion</h1>

<%= render "form", ingestion: @ingestion %>

<br>

<div>
  <%= link_to "Show this ingestion", @ingestion %> |
  <%= link_to "Back to ingestions", ingestions_path %>
</div>

app/views/ingestions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingestions</h1>

<div id="ingestions">
  <% @ingestions.each do |ingestion| %>
    <%= render ingestion %>
    <p>
      <%= link_to "Show this ingestion", ingestion %>
    </p>
  <% end %>
</div>

<%= link_to "New ingestion", new_ingestion_path %>

app/views/ingestions/new.html.erb
<h1>New ingestion</h1>

<%= render "form", ingestion: @ingestion %>

<br>

<div>
  <%= link_to "Back to ingestions", ingestions_path %>
</div>

app/views/ingestions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingestion %>

<div>
  <%= link_to "Edit this ingestion", edit_ingestion_path(@ingestion) %> |
  <%= link_to "Back to ingestions", ingestions_path %>

  <%= button_to "Destroy this ingestion", @ingestion, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeedBeDown</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
  <strong>Name:</strong>
  <%= user.name %>
  </p>
  <div id="ingestions">
    <% user.ingestions.each do |i| %>
      <%= render i %>
      <p>
      <%= link_to "Show this ingestion", i %>
      </p>
    <% end %>
  </div>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= user.name %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>